### ISSUE TITLE
Variable coordinate Error

### ISSUE THREAD

**Issue by Naff16** [MirnaZohiry/RaspberryPi_Camera_Scanner#1]
Hello,
im getting this error:
```
Traceback (most recent call last):
  File "Scanner.py", line 68, in <module>
    main()
  File "Scanner.py", line 44, in main
    points_old = coordinate
UnboundLocalError: local variable 'coordinate' referenced before assignment
```
How can i solve this?
Best regards

**Comment by MirnaZohiry** [comment]
Hello, 
Make sure you have coordinate initialized before this line of code. It's initialized in the if statement "if len(approx) == 4:". Please make sure your image taken with the pi camera includes an object that has four dimensions which would occur if you have a piece of paper in the image.

**Comment by Naff16** [comment]
Hello,
the problem was solved, i didnt realize about the image 4 dimensions. I taked a picture of the full sheet and work like a charm.
Thanks
